### ISSUE TITLE
Errors when testing

### ISSUE THREAD

**Issue by HappyDay-design** [alexDS12/traffic-light-dqnagent#2]
Hello

I trained your model but i can not test your model.

(TF2) osboxes@osboxes:~/Desktop/traffic-light-dqnagent$ python main.py
Select option: 
(1) Training (2) Testing 2
Model found
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    main_testing()
  File "main.py", line 23, in main_testing
    agent = DQNAgent(nn = nn)
TypeError: __init__() missing 4 required positional arguments: 'memory_size', 'discount_rate', 'batch_size', and 'epochs'

**Comment by WDWLWY** [comment]
Hello, I have the same problem. Have you solved your problem？

**Comment by HappyDay-design** [comment]
> Hello, I have the same problem. Have you solved your problem？

You could use other source codes to train and test
https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control

**Comment by WDWLWY** [comment]
Hello, excuse me. Do you have the source code of DQN controlling single intersection?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
Hello, I have the same problem. Have you solved your problem？
  
You could use other source codes to train and test
 https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control

**Comment by WDWLWY** [comment]
Hello,&nbsp;
I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
Hello, I have the same problem. Have you solved your problem？
  
You could use other source codes to train and test
 https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control

**Comment by HappyDay-design** [comment]
> Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" ***@***.***&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Hello. About MARL you could use this repository
https://github.com/cts198859/deeprl_network

[Tensorflow](http://www.tensorflow.org/install) == 1.13.1
[SUMO](http://sumo.dlr.de/wiki/Installing) >= 1.1.0

**Comment by WDWLWY** [comment]
https://github.com/cts198859/deeprl_network.git
您好，请问这个文件你可以正常运行嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Hello. About MARL you could use this repository
 https://github.com/cts198859/deeprl_network.git

**Comment by WDWLWY** [comment]
When I try to run this code, it defaults to DEFAULT_ PORT=8000. But an error was reported: Error: tcpip:: Socket:: accept() Unable to create listening socket: Address already in use.

https://github.com/cts198859/deeprl_network.git





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Hello. About MARL you could use this repository
 https://github.com/cts198859/deeprl_network.git

**Comment by HappyDay-design** [comment]
> When I try to run this code, it defaults to DEFAULT_ PORT=8000. But an error was reported: Error: tcpip:: Socket:: accept() Unable to create listening socket: Address already in use. https://github.com/cts198859/deeprl_network.git
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" ***@***.***&gt;; 发送时间:&nbsp;2023年6月5日(星期一) 上午10:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; Hello. About MARL you could use this repository https://github.com/cts198859/deeprl_network.git — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

I can run all repo

**Comment by WDWLWY** [comment]
Do you use a CPU or GPU?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
When I try to run this code, it defaults to DEFAULT_ PORT=8000. But an error was reported: Error: tcpip:: Socket:: accept() Unable to create listening socket: Address already in use. https://github.com/cts198859/deeprl_network.git
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年6月5日(星期一) 上午10:33 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; Hello. About MARL you could use this repository https://github.com/cts198859/deeprl_network.git — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
I can run all repo

**Comment by HappyDay-design** [comment]
> Do you use a CPU or GPU?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" ***@***.***&gt;; 发送时间:&nbsp;2023年6月14日(星期三) 晚上10:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) When I try to run this code, it defaults to DEFAULT_ PORT=8000. But an error was reported: Error: tcpip:: Socket:: accept() Unable to create listening socket: Address already in use. https://github.com/cts198859/deeprl_network.git … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年6月5日(星期一) 上午10:33 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; Hello. About MARL you could use this repository https://github.com/cts198859/deeprl_network.git — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; I can run all repo — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

CPU

**Comment by WDWLWY** [comment]
The CPU runs for a long time once




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 上午9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
Do you use a CPU or GPU?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年6月14日(星期三) 晚上10:20 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) When I try to run this code, it defaults to DEFAULT_ PORT=8000. But an error was reported: Error: tcpip:: Socket:: accept() Unable to create listening socket: Address already in use. https://github.com/cts198859/deeprl_network.git … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年6月5日(星期一) 上午10:33 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; Hello. About MARL you could use this repository https://github.com/cts198859/deeprl_network.git — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; I can run all repo — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
CPU

**Comment by WDWLWY** [comment]
Hello, regarding this code：“https://github.com/cts198859/deeprl_network.git”，When testing after training, the queue length is shown as follows: it is completely different from what was mentioned in someone else's paper. What is the situation? What was the queue length curve like during your testing?------------------&nbsp;原始邮件&nbsp;------------------




发件人:                                                                                                                        "alexDS12/traffic-light-dqnagent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 上午9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2)





  
Do you use a CPU or GPU?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年6月14日(星期三) 晚上10:20 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) When I try to run this code, it defaults to DEFAULT_ PORT=8000. But an error was reported: Error: tcpip:: Socket:: accept() Unable to create listening socket: Address already in use. https://github.com/cts198859/deeprl_network.git … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年6月5日(星期一) 上午10:33 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello,&nbsp; I saw that you consulted a project called "sumo multiagent" on GitHub. Can this code run? If possible, which version of TensorFlow should be used? Thank you … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexDS12/traffic-light-dqnagent" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alexDS12/traffic-light-dqnagent] Errors when testing (Issue #2) Hello, I have the same problem. Have you solved your problem？ You could use other source codes to train and test https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; Hello. About MARL you could use this repository https://github.com/cts198859/deeprl_network.git — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; I can run all repo — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
CPU

**Comment by alexDS12** [comment]
Close #08dae39

**Comment by alexDS12** [comment]
fixed testing code in 08dae394bdac16678fba8587095f3fd1f2d00029
